### ISSUE TITLE
Issue starting NoiseModelling 4.0.5 under Windows 11 using the .exe version

### ISSUE THREAD

**Issue by CodeMazeSolver** [Universite-Gustave-Eiffel/NoiseModelling#716]
Hello,
sadly I'm unable to test this interesting tool. I tried to use the Windows variant and also did some tests with the .zip version. However, I also ran into some issues there, too.

**NoiseModelling version**
NoiseModelling **4.0.5**

**Describe the bug**
When I start the application, I see the command window which opens and loads some stuff correctly.
However, I will get the following error message before the window closes itself:

```bash
WARN : oejx.XmIConfiguration:main:
java.security.PriviIegedActionException: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:7654
at java.base/java.security.AccessController.doPriviIeged(Native Method)
at org.eclipse.jetty.xmI.XmlConfiguration.main.java : 1881)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpI.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpI.invoke(NativeMethodAccessorImpI.java : 62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpI.invoke(DeIegatingMethodAccessorImp1.java : 43)
at java.base/java.lang.reflect.Method.invoke(method.java : 566)
at org.eclipse.jetty.start.Main.invokehain (Main.java : 218)
at org.eclipse.jetty.start.Main.start Chain.java : 491)
at org.eclipse.jetty.start.Main.main (Main.java : 77)
```

**To Reproduce**
1. Start the application using the .exe file
2. See error

**Geoserver log**
So far no logs have been created.

**Expected behavior**
That NoiseModelling starts up normally

**Screenshots**
![grafik](https://github.com/user-attachments/assets/783d3e87-4dd6-44a3-a7a3-7fc4931e3661)

![grafik](https://github.com/user-attachments/assets/815ebeb2-bc61-47fe-a9f8-e483f5e40c90)

**Additional context**
I already had GeoServer installed beforehand using port: 7654

As I get the same error using the .zip distributed variant, I assume that the error might be due to my already installed version of GeoServer.

**Comment by Nitnelav** [comment]
You're right, you can't have more than one process listening on the same port basically, in this case port 7654. You should terminate the exisiting geoserver or configure it to use another port. You could tweak the geoserver shipped with noisemodelling to use another port also but I don't know how...

**Comment by CodeMazeSolver** [comment]
I worked with a Docker container as explained in the documentation.
I'll try changing the port number of my existing GeoServer. However, regarding the port selection there should be an option for NoiseModelling to change the default port. There might be a situation in which a user cannot use the default port required by GeoServer as it is occupied by another application that cannot be changed that easily.

**Comment by Nitnelav** [comment]
There is a start.ini at the root of the NoiseModelling folder (in the zip package).
at line 144 you should see this :

```ini
# HTTP port to listen on
jetty.http.port=9580
```

You should be able to change it and start NoiseModelling again

**Comment by Nitnelav** [comment]
A couple of weird things in your post though :

- You mention the EXE, then you mention DOCKER, and you also mention the ZIP ... which one are you using exactly 
- Your logs seem to come from a Geoserver that is not packaged with noisemodelling : `C:\Program Files\Geoserver`
- The 7654 port is not the one we use by default. It is 9580. So maybe it has nothing to do with NoiseModelling.

**Comment by CodeMazeSolver** [comment]
> A couple of weird things in your post though :
> 
>     * You mention the EXE, then you mention DOCKER, and you also mention the ZIP ... which one are you using exactly
> 
>     * Your logs seem to come from a Geoserver that is not packaged with noisemodelling : `C:\Program Files\Geoserver`
> 
>     * The 7654 port is not the one we use by default. It is 9580. So maybe it has nothing to do with NoiseModelling.

1. I started using the .exe version &rarr; This did not work and through the error shown above.
2. I then used the .zip version &rarr. This did not work either, and I got the same error message.
Thus, it must be something with the GeoServer port, which is 7654 in my instance.

I had another look at the documentation and found that there are some Docker images available. So I used one of those to do some testing and this worked out of the box.

**Comment by CodeMazeSolver** [comment]
> There is a start.ini at the root of the NoiseModelling folder (in the zip package). at line 144 you should see this :
> 
> ```ini
> # HTTP port to listen on
> jetty.http.port=9580
> ```
> 
> You should be able to change it and start NoiseModelling again

I changed the port to something different as you suggested. However, I still get the same error message. I will now uninstall GeoServer on my machine then install NoiseModelling again and test if this solves the issue.

**Comment by Nitnelav** [comment]
Mmm I still don't understand why there is a c:\program files\geoserver in the logs.

**Comment by Nitnelav** [comment]
Ah ok, I found the reason. The startup script is a .bat file that checks for the `GEOSERVER_HOME` environment variable.
If it doesn't exist it is set to the right location, in our case : `Z:\PATH\TO\NoiseModelling_4.0.X\` 
In your situation it is already set to `C:\Program Files\Geoserver`, and so it is this one that is launched instead of the one packaged with NoiseModelling.
And if it is already running, whatever the port number you set, it is going to fail because it is going to start with the same config and so try to bind to the same port.

If you mess with the environment variable just before running the exe it should work (from powershell) :

```powershell
cmd /C "set GEOSERVER_HOME=WRONG_ON_PURPOSE && set && .\NoiseModelling.exe"
```
